config/routes.rb
Rails.application.routes.draw do
  get "webmanifest"    => "pwa#manifest"
  get "service-worker" => "pwa#service_worker"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "uikit" => "pages#uikit"
  # Defines the root path route ("/")
  # root "posts#index"
  devise_for :users

  authenticate :user, ->(user) { user.admin? } do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end

  root to: "pages#home"

  resources :objectives

  resources :todos, only: [:show]

  resources :tasks, only: [:index, :update] do
    member do
      patch :uncomplete
      patch :complete
    end
  end

  get "todos/:id/next_day", to: "todos#next_day", as: :next_day

  get "/stats", to: "stats#index", as: :stats

  get "/stats/objectives", to: "stats#objectives", as: :stats_objectives

end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # before_action :set_task, except: [:update]

  def index
    @tasks = Task.all
  end

  # def update
  #   @task = Task.find(params[:id])
  #   @task.update(completed: true)
  #   redirect_to todo_path(@task.todo.objective)
  # end

  def complete
    @task = Task.find(params[:id])
    @task.update(completed: true)
    @objective = @task.todo.objective
    tasks = @task.todo.tasks

    @todos_completed = tasks.count == tasks.where(completed: true).count
    if @todos_completed
      @task.todo.update(completed: true)
    end

    @objective_completed = @objective.todos.count == @objective.todos.where(completed: true).count
    if @objective_completed
      @objective.update(completed: true)
    end

    respond_to do |format|
      format.turbo_stream
    end
  end

  def uncomplete
    @task = Task.find(params[:id])
    @task.update(completed: false)
    @task.todo.update(completed: false)
    @task.todo.objective.update(completed: false)

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(
      :title,
      :ressource_ia,
      :completed,
      :priority,
      :completed_at,
      :todo_id
    )
  end
end

app/views/tasks/_complete_card.html.erb
<div id="<%= dom_id(task) %>" class="todo-carte" data-controller="task-help" data-completed="true">
  <div class="todo-carte-header">
    <%= link_to uncomplete_task_path(task), data: { turbo_method: :patch, turbo: true } do %>
    <!-- Partie gauche : checkbox + titre centrés verticalement -->
    <div class="header-left">
        <!-- Checkbox complétée -->
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 48 48">
          <g fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="4">
            <path d="M24 44a19.94 19.94 0 0 0 14.142-5.858A19.94 19.94 0 0 0 44 24a19.94 19.94 0 0 0-5.858-14.142A19.94 19.94 0 0 0 24 4A19.94 19.94 0 0 0 9.858 9.858A19.94 19.94 0 0 0 4 24a19.94 19.94 0 0 0 5.858 14.142A19.94 19.94 0 0 0 24 44Z"/>
            <path stroke-linecap="round" d="m16 24l6 6l12-12"/>
          </g>
        </svg>

      <p class="todo-title"><%= task.title %></p>
    </div>
    <% end %>

  </div>

  <!-- Summary caché par défaut -->
  <div class="task-summary" data-task-help-target="body" style="">
    <p><%= task.ressource_ia %></p>
  </div>
</div>

app/views/tasks/_uncomplete_card.html.erb
<div id="<%= dom_id(task) %>" class="todo-carte" data-controller="task-help" data-completed="<%= task.completed %>">
  <div class="todo-carte-header">
    <!-- Partie gauche : checkbox + divider + titre -->
    <div class="header-left">
      <% if task.completed %>
        <%= link_to uncomplete_task_path(task), data: { turbo_method: :patch, turbo: true }, id: dom_id(task) do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 48 48">
            <g fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="4">
              <path d="M24 44a19.94 19.94 0 0 0 14.142-5.858A19.94 19.94 0 0 0 44 24a19.94 19.94 0 0 0-5.858-14.142A19.94 19.94 0 0 0 24 4A19.94 19.94 0 0 0 9.858 9.858A19.94 19.94 0 0 0 4 24a19.94 19.94 0 0 0 5.858 14.142A19.94 19.94 0 0 0 24 44Z"/>
              <path stroke-linecap="round" d="m16 24l6 6l12-12"/>
            </g>
          </svg>
        <% end %>
      <% else %>
        <%= link_to complete_task_path(task), data: { turbo_method: :patch, turbo: true }, id: dom_id(task) do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 48 48">
            <g fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="4">
              <path d="M24 44a19.94 19.94 0 0 0 14.142-5.858A19.94 19.94 0 0 0 44 24a19.94 19.94 0 0 0-5.858-14.142A19.94 19.94 0 0 0 24 4A19.94 19.94 0 0 0 9.858 9.858A19.94 19.94 0 0 0 4 24a19.94 19.94 0 0 0 5.858 14.142A19.94 19.94 0 0 0 24 44Z"/>
            </g>
          </svg>
        <% end %>
      <% end %>

      <div class="vertical-divider"></div>

      <p class="todo-title"><%= task.title %></p>
    </div>

    <!-- Point d'interrogation -->
    <span class="card-help" data-action="click->task-help#toggle">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
          <path fill="currentColor" d="M12 22C6.477 22 2 17.523 2 12S6.477 2 12 2s10 4.477 10 10s-4.477 10-10 10m0-2a8 8 0 1 0 0-16a8 8 0 0 0 0 16m-1-5h2v2h-2zm2-1.645V14h-2v-1.5a1 1 0 0 1 1-1a1.5 1.5 0 1 0-1.471-1.794l-1.962-.393A3.501 3.501 0 1 1 13 13.355"/>
        </svg>
    </span>
  </div>

  <!-- Résumé caché par défaut -->
  <div data-task-help-target="body" class="task-summary">
    <p><%= task.ressource_ia %></p>
  </div>
</div>

app/views/tasks/complete.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@task)) do %>
  <%= render partial: "tasks/complete_card", locals: { task: @task } %>
<% end %>

<% if @objective_completed %>
  <%= turbo_stream.replace(dom_id(@task.todo, "next_todo")) do %>
    <div id="<%= dom_id(@task.todo, "next_todo") %>">
      <p>Bravo, vous avez atteint votre objectif !</p>
      <%= link_to "VOIR MES OBJECTIFS", objectives_path(@objective), class: "bouton fokus-btn" %>
    </div>
  <% end %>
<% end %>

<% if !@objective_completed && @task.todo.completed? %>
  <%= turbo_stream.replace(dom_id(@task.todo, "next_todo")) do %>
    <%= link_to "JOUR SUIVANT", next_day_path(@task.todo), class: "bouton fokus-btn", id: dom_id(@task.todo, "next_todo") %>
  <% end %>
<% end %>

<% if @task.priority == 1 %>
  <%= turbo_stream.replace("fokus-btn") do %>
    <a href="#" class="bouton w-100 my-2 fokus-btn d-none"
      data-bs-toggle="modal"
      data-bs-target="#fokusModal"
      data-task-name="<%= @task.title %>"
      id="fokus-btn">
      FOKUS
    </a>
  <% end %>
<% end %>

app/views/tasks/show.html.erb
<h1>Tasks show</h1>

<% if todo.tasks.any? %>
          <ul>
            <% todo.tasks.order(:priority).each do |task| %>
              <li>
                <strong><%= task.title %></strong>
                <% if task.ressource_ia.present? %>
                  - <a href="<%= task.ressource_ia %>" target="_blank">Ressource IA</a>
                <% end %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>Aucune tâche pour ce jour.</p>
        <% end %>
      </div>
    </div>
  <% end %>
<% else %>
  <p>Aucun programme généré pour cet objectif.</p>
<% end %>

<%= link_to "Retour aux objectifs", objectives_path, class: "btn btn-secondary mt-3" %>

app/views/tasks/uncomplete.turbo_stream.erb
<%= turbo_stream.replace(dom_id(@task)) do %>
  <%= render partial: "tasks/uncomplete_card", locals: { task: @task } %>
<% end %>

<%= turbo_stream.replace(dom_id(@task.todo, "next_todo")) do %>
  <div id="<%= dom_id(@task.todo, "next_todo") %>"></div>
<% end %>

<% if @task.priority == 1 %>
  <%= turbo_stream.replace("fokus-btn") do %>
    <a href="#" class="bouton w-100 my-2 fokus-btn"
       data-bs-toggle="modal"
       data-bs-target="#fokusModal"
       data-task-name="<%= @task.title %>"
       id="fokus-btn">
       FOKUS
    </a>
  <% end %>
<% end %>