config/routes.rb
Rails.application.routes.draw do
  get "webmanifest"    => "pwa#manifest"
  get "service-worker" => "pwa#service_worker"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "uikit" => "pages#uikit"
  # Defines the root path route ("/")
  # root "posts#index"
  devise_for :users

  authenticate :user, ->(user) { user.admin? } do
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end

  root to: "pages#home"

  resources :objectives

  resources :todos, only: [:show]

  resources :tasks, only: [:index, :update] do
    member do
      patch :uncomplete
      patch :complete
    end
  end

  get "todos/:id/next_day", to: "todos#next_day", as: :next_day

  get "/stats", to: "stats#index", as: :stats

  get "/stats/objectives", to: "stats#objectives", as: :stats_objectives

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fokus sur vos objectifs</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
    <meta name="mobile-web-app-capable" content="yes">
    <%= tag.link rel: "manifest", href: webmanifest_path(format: :json) %>
    <%= tag.link rel: "icon", href: image_url("icon.png"), type: "image/png" %>
    <%= tag.link rel: "apple-touch-icon", href: image_url("icon.png") %>
    <meta property="og:title" content="Fokus sur vos objectifs">
    <meta property="og:description" content="Fokus génère un plan d’action personnalisé selon vos objectifs.">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.fokus-app.me">
    <meta property="og:image" content="<%= image_url('og.png') %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

<body data-controller="sidebar">

  <%= render "shared/navbar" %>
  <%= render "shared/sidebar" %>

  <!-- OVERLAY -->
  <div class="overlay hidden"
       data-sidebar-target="overlay"
       data-action="click->sidebar#toggle"></div>

  <!-- CONTENU -->
  <div class="content-wrapper" data-sidebar-target="content">
      <%= yield %>
  </div>

</body>
</html>